/****************************************************************************** *
 * Module: ultra-sonic Sensor
 *
 * File Name: ultra_sensor.c
 *
 * Description: source file for the HCSR04 Ultra-sonic sensor driver
 *
 * Author: mustafa awad
 *******************************************************************************/

#include "ultra_sensor.h"

#include "common_macros.h"
#include "gpio.h"               /*for set trigger pin*/
#include "icu.h"
#include <util/delay.h>


volatile static uint8 edge_Count = 0;
volatile static uint16 time_High_Pulse = 0;


void Ultrasonic_init(void){


	/* Create configuration structure for ICU driver */
	Icu_ConfigType Icu_Config = {F_CPU_8,RISING};
	Icu_init(&Icu_Config);
	/* Set the Call back function pointer in the ICU driver */
	Icu_setCallBack(Ultrasonic_edgeProcessing);

	GPIO_setupPinDirection(TRIGGERING_PORT, TRIGGERING_PIN, PIN_OUTPUT);

}

/* Description:
 *  the Trigger pulse to the ultra-sonic
 * */
void Ultrasonic_Trigger(void){


	GPIO_writePin(TRIGGERING_PORT, TRIGGERING_PIN, LOGIC_HIGH);
	_delay_us(15);
	GPIO_writePin(TRIGGERING_PORT, TRIGGERING_PIN, LOGIC_LOW);

}

/* Description:
 *  Start the measurements by the ICU
 * return The measured distance in cm
  */
uint16 Ultrasonic_readDistance(void){

	uint16 dist = 0 ;
	Ultrasonic_Trigger();

	if (edge_Count==2)
	{

		edge_Count = 0;
		dist =((float)time_High_Pulse/57.5);
	}

	return dist ;
}


/* Description:
 *  used to calculate the pulse time generated by the ultra-sonic sensor
 */
void Ultrasonic_edgeProcessing(void){

	edge_Count++;
	if(edge_Count == 1)
	{

		Icu_clearTimerValue();

		Icu_setEdgeDetectionType(FALLING);
	}
	else if(edge_Count == 2)
	{

		time_High_Pulse = Icu_getInputCaptureValue();

		Icu_clearTimerValue();

		Icu_setEdgeDetectionType(RISING);
	}
}

